### ISSUE TITLE
Race conditions in AppointmentService

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [fs-anvr/medical_service#7]
You have multiple race conditions in AppointmentService. The way you are approaching the dictionary of `SempaphoreSlim` misses a lot of tricks. I have written a library that can handle all this for you at https://www.nuget.org/packages/AsyncKeyedLock

**Comment by fsanvr** [comment]
"Issues" is not intended for advertising.

**Comment by MarkCiliaVincenti** [comment]
You miss the whole point. I'm not "selling you" anything but rather warning you about existing issues within your code, but it seems you have an issue (pun intended) with accepting constructive criticism and help.

**Comment by fsanvr** [comment]
You're missing the point - you opened the question without writing the question. Also, if you are talking about errors in my code, please speak specifically. There is an error statement in your messages, but there is no specifics. If you have objective arguments in favor of your library, you can also write them.

**Comment by MarkCiliaVincenti** [comment]
If you can't see the problem, that speaks about you needing to use a library though.

Let me help you.... so let's say thread A calls CreateAppointment(AppointmentForm form) where form.DoctorId = 1.
Thread A will create an entry in semaphoreByDoctor, correct?

Now while this is being processed, thread B also calls CreateAppointment(AppointmentForm form) where form.DoctorId = 1.
Thread B will read the same semaphoreslim from semaphoreByDoctor and share it with thread A, waiting to enter the thread.

Now thread A finishes and removes the item from semaphoreByDoctor. Thread B enters the semaphore (which is still not disposed) and starts processing

Now thread C comes along and also calls CreateAppointment(AppointmentForm form) where form.DoctorId = 1. But it will not find the semaphore in the dictionary, so it will create a new one and start processing for doctorid = 1 whilst thread B is doing the same thing.

Is this not what you're trying to avoid?
